name: flutter_app_demo
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # ----- 工具 库 -----------
  dio: ^5.1.1 # 网络请求
  connectivity: ^3.0.6 # 网络监控
  event_bus: ^2.0.0 # 事件通知: 注意通知关闭的时机
  provider: ^6.0.5 # 状态管理: 建议单个页面单个Provider，多个页面合用一个provider容易出现数据未清除问题
  uuid: ^3.0.7 #flutter侧的UUID生成器
  path: ^1.8.2 #Dart 路径操作库
  equatable: ^2.0.5 #对象比较库
  json_serializable: ^6.6.1 # json解析
  shared_preferences: ^2.1.0 # 本地存储
  path_provider: ^2.0.14 # 本地路径查询，实现清除缓存功能
  permission_handler: ^10.2.0 # 权限申请
  flutter_boost: # flutter和原生混合
    git:
      url: 'https://github.com/alibaba/flutter_boost.git'
      ref: '4.0.2'
  go_router: ^7.0.1 # 路由导航



  # ----- UI 库 -----------
  flutter_screenutil: ^5.7.0 # 屏幕适配
  flutter_staggered_grid_view: ^0.6.2 # 瀑布流
  image_picker: ^0.8.7+4 #图片选择器
  fluttertoast: ^8.2.1 # toast
  flutter_easyloading: ^3.0.5 # 网络加载loading
  scrollable_positioned_list: ^0.3.5 #列表工具库，可以指定滚动位置
  badges: ^3.1.1 #提示组件库(例：未读小红点)
  pull_to_refresh: ^2.0.0 #下拉刷新库
  gzx_dropdown_menu: ^3.1.0 #下拉筛选菜单
  cached_network_image: ^3.2.3 #加载并缓存图像库
  flutter_inappwebview: ^5.7.2+3 # 官方web
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
